package dev.dsmirnov.photoframe.data

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import dev.dsmirnov.photoframe.protocol.FrameIdentity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import android.util.Base64

private val Context.identityDataStore by preferencesDataStore(name = "framealt_identity")

/**
 * Stores this client's long-term X25519 private key.
 *
 * **The key is the pairing.** Anyone holding it can send to every frame paired with it, and
 * losing it means pairing again with a fresh friend code from the frame.
 *
 * It lives in app-private DataStore, wrapped with an AES-256-GCM key held in the Android
 * Keystore (StrongBox when the device has it). That is the pattern Google moved to after
 * deprecating `androidx.security:security-crypto` / `EncryptedSharedPreferences`, which
 * suffered keyset corruption and main-thread I/O on some OEM builds.
 *
 * `setUserAuthenticationRequired(false)` is deliberate: background sends must work with the
 * screen locked, which is the whole point of the queue in D7.
 */
class IdentityStore(private val context: Context) {

    private val mutex = Mutex()

    /** Returns the stored identity, generating one on first use. */
    suspend fun identity(): FrameIdentity = mutex.withLock {
        withContext(Dispatchers.IO) {
            val stored = context.identityDataStore.data.first()[KEY_WRAPPED]
            if (stored != null) {
                FrameIdentity.fromPrivateKey(unwrap(stored))
            } else {
                val fresh = FrameIdentity.generate()
                context.identityDataStore.edit { it[KEY_WRAPPED] = wrap(fresh.exportPrivateKey()) }
                fresh
            }
        }
    }

    /** True once an identity exists. Used by diagnostics; does not create one. */
    suspend fun exists(): Boolean = withContext(Dispatchers.IO) {
        context.identityDataStore.data.first()[KEY_WRAPPED] != null
    }

    // --- Keystore wrapping --------------------------------------------------------------

    private fun wrap(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.US_ASCII))
        // The GCM IV is generated by the provider and must be stored with the ciphertext.
        return Base64.encodeToString(cipher.iv, Base64.NO_WRAP) + ":" +
            Base64.encodeToString(ciphertext, Base64.NO_WRAP)
    }

    private fun unwrap(stored: String): String {
        val parts = stored.split(":")
        require(parts.size == 2) { "stored identity is malformed" }
        val iv = Base64.decode(parts[0], Base64.NO_WRAP)
        val ciphertext = Base64.decode(parts[1], Base64.NO_WRAP)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        return cipher.doFinal(ciphertext).toString(Charsets.US_ASCII)
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        // StrongBox is a hardware security module; not every device has one, and asking for
        // it on a device without one throws rather than degrading.
        return try {
            generateKey(strongBox = true)
        } catch (_: StrongBoxUnavailableException) {
            generateKey(strongBox = false)
        }
    }

    private fun generateKey(strongBox: Boolean): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setUserAuthenticationRequired(false)
                .setIsStrongBoxBacked(strongBox)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        val KEY_WRAPPED = stringPreferencesKey("identity.wrapped")
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val ALIAS = "framealt.identity.wrapper"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
    }
}
