// Generates the crypto test vectors for :protocol.
//
// Why this exists: our Kotlin NaCl is *composed* from BouncyCastle primitives. An
// implementation that seals and opens its own messages happily can still be wrong in a
// way no round-trip test catches. So every vector here comes from tweetnacl-js — a pure
// JavaScript NaCl with no shared lineage with either our Kotlin/BouncyCastle port or the
// Go reference client.
//
// X25519 and Ed25519 are additionally cross-checked against Node's OpenSSL bindings, so
// two independent implementations must agree before anything is written to disk.
//
// Usage:  npm install && npm run gen
// Output: protocol/src/test/resources/vectors/*.json

import nacl from 'tweetnacl'
import { createHash, createPrivateKey, createPublicKey, diffieHellman, verify as cryptoVerify } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = join(HERE, '..', '..', 'protocol', 'src', 'test', 'resources', 'vectors')

const ORIGIN =
  'Generated by tools/gen-vectors/generate.mjs from tweetnacl-js (an independent NaCl ' +
  'implementation), cross-checked against Node/OpenSSL where applicable. Do not hand-edit.'

// --- deterministic byte source -------------------------------------------------------
// A counter hashed with SHA-256, so regenerating produces byte-identical files and diffs
// stay meaningful.
let counter = 0
function bytes(n) {
  const out = new Uint8Array(n)
  let filled = 0
  while (filled < n) {
    const block = createHash('sha256').update(`framealt-vector-${counter++}`).digest()
    const take = Math.min(block.length, n - filled)
    out.set(block.subarray(0, take), filled)
    filled += take
  }
  return out
}

const hex = (u8) => Buffer.from(u8).toString('hex')

// --- OpenSSL cross-checks ------------------------------------------------------------
const X25519_PKCS8_PREFIX = Buffer.from('302e020100300506032b656e04220420', 'hex')
const X25519_SPKI_PREFIX = Buffer.from('302a300506032b656e032100', 'hex')
const ED25519_SPKI_PREFIX = Buffer.from('302a300506032b6570032100', 'hex')

/** The X25519 base point, u = 9. */
const X25519_BASE_POINT = (() => {
  const p = new Uint8Array(32)
  p[0] = 9
  return p
})()

function opensslX25519(scalar, point) {
  const privateKey = createPrivateKey({
    key: Buffer.concat([X25519_PKCS8_PREFIX, Buffer.from(scalar)]),
    format: 'der',
    type: 'pkcs8',
  })
  const publicKey = createPublicKey({
    key: Buffer.concat([X25519_SPKI_PREFIX, Buffer.from(point)]),
    format: 'der',
    type: 'spki',
  })
  return new Uint8Array(diffieHellman({ privateKey, publicKey }))
}

function opensslEd25519Verify(publicKey, message, signature) {
  const key = createPublicKey({
    key: Buffer.concat([ED25519_SPKI_PREFIX, Buffer.from(publicKey)]),
    format: 'der',
    type: 'spki',
  })
  return cryptoVerify(null, Buffer.from(message), key, Buffer.from(signature))
}

function assertSame(label, a, b) {
  if (hex(a) !== hex(b)) {
    throw new Error(`cross-check FAILED for ${label}:\n  tweetnacl: ${hex(a)}\n  openssl:   ${hex(b)}`)
  }
}

// --- vectors -------------------------------------------------------------------------

function hsalsa20Vectors() {
  const sigma = new Uint8Array(Buffer.from('expand 32-byte k', 'ascii'))
  const cases = [
    { note: 'zero input — the crypto_box_beforenm shape', key: bytes(32), input: new Uint8Array(16) },
    { note: 'zero key', key: new Uint8Array(32), input: bytes(16) },
    { note: 'all zero', key: new Uint8Array(32), input: new Uint8Array(16) },
    ...Array.from({ length: 6 }, () => ({ note: 'random', key: bytes(32), input: bytes(16) })),
  ]
  return cases.map(({ note, key, input }) => {
    const out = new Uint8Array(32)
    nacl.lowlevel.crypto_core_hsalsa20(out, input, key, sigma)
    return { note, key: hex(key), input: hex(input), output: hex(out) }
  })
}

function xsalsa20Vectors() {
  // Lengths that straddle the 64-byte Salsa20 block boundary, plus the 32-byte shape PACE
  // uses to decrypt its mapping scalar.
  const lengths = [0, 1, 31, 32, 33, 63, 64, 65, 97, 128, 1000]
  return lengths.map((length) => {
    const key = bytes(32)
    const nonce = bytes(24)
    const input = bytes(length)
    const out = new Uint8Array(length)
    if (length > 0) {
      nacl.lowlevel.crypto_stream_xor(out, 0, input, 0, length, nonce, key)
    }
    return {
      note: `${length} bytes`,
      key: hex(key),
      nonce: hex(nonce),
      input: hex(input),
      output: hex(out),
    }
  })
}

function secretBoxVectors() {
  // 0 and 32 matter because the Poly1305 subkey is the first 32 keystream bytes; a
  // bug in where the message starts shows up exactly at those boundaries.
  const lengths = [0, 1, 15, 16, 17, 31, 32, 33, 64, 127, 128, 1000]
  return lengths.map((length) => {
    const key = bytes(32)
    const nonce = bytes(24)
    const message = bytes(length)
    const boxed = nacl.secretbox(message, nonce, key)
    if (!boxed) throw new Error('tweetnacl secretbox returned null')
    return {
      note: `${length}-byte message`,
      key: hex(key),
      nonce: hex(nonce),
      message: hex(message),
      boxed: hex(boxed),
    }
  })
}

function boxVectors() {
  const lengths = [0, 1, 32, 64, 128, 500]
  return lengths.map((length) => {
    const sender = nacl.box.keyPair.fromSecretKey(bytes(32))
    const recipient = nacl.box.keyPair.fromSecretKey(bytes(32))
    const nonce = bytes(24)
    const message = bytes(length)
    const boxed = nacl.box(message, nonce, recipient.publicKey, sender.secretKey)
    const shared = nacl.box.before(recipient.publicKey, sender.secretKey)

    // The receiving side must derive the identical shared key.
    const reverse = nacl.box.before(sender.publicKey, recipient.secretKey)
    assertSame('box.before symmetry', shared, reverse)

    return {
      note: `${length}-byte message`,
      senderPublicKey: hex(sender.publicKey),
      senderSecretKey: hex(sender.secretKey),
      recipientPublicKey: hex(recipient.publicKey),
      recipientSecretKey: hex(recipient.secretKey),
      nonce: hex(nonce),
      message: hex(message),
      boxed: hex(boxed),
      sharedKey: hex(shared),
    }
  })
}

function x25519Vectors() {
  const vectors = []
  for (let i = 0; i < 8; i++) {
    const scalar = bytes(32)
    const peerSecret = bytes(32)
    const point = nacl.scalarMult.base(peerSecret)
    const shared = nacl.scalarMult(scalar, point)
    assertSame(`x25519 #${i}`, shared, opensslX25519(scalar, point))

    // scalarMultBase(k) must equal scalarMult(k, basePoint) where the base point is u = 9.
    const base = nacl.scalarMult.base(scalar)
    assertSame(`x25519 base #${i}`, base, opensslX25519(scalar, X25519_BASE_POINT))

    vectors.push({
      note: `random pair ${i}`,
      scalar: hex(scalar),
      point: hex(point),
      shared: hex(shared),
      scalarMultBase: hex(base),
    })
  }
  return vectors
}

function ed25519Vectors() {
  const vectors = []
  for (let i = 0; i < 6; i++) {
    const seed = bytes(32)
    const pair = nacl.sign.keyPair.fromSeed(seed)
    const message = bytes(i * 37)
    const signature = nacl.sign.detached(message, pair.secretKey)

    if (!nacl.sign.detached.verify(message, signature, pair.publicKey)) {
      throw new Error('tweetnacl failed to verify its own signature')
    }
    if (!opensslEd25519Verify(pair.publicKey, message, signature)) {
      throw new Error(`cross-check FAILED: OpenSSL rejected a valid tweetnacl signature (#${i})`)
    }

    vectors.push({
      note: `${message.length}-byte message`,
      publicKey: hex(pair.publicKey),
      message: hex(message),
      signature: hex(signature),
      valid: true,
    })

    // Negative case: flip one bit of the signature. Must be rejected.
    const tampered = Uint8Array.from(signature)
    tampered[i % tampered.length] ^= 0x01
    if (nacl.sign.detached.verify(message, tampered, pair.publicKey)) {
      throw new Error('tweetnacl accepted a tampered signature')
    }
    vectors.push({
      note: `${message.length}-byte message, one signature bit flipped`,
      publicKey: hex(pair.publicKey),
      message: hex(message),
      signature: hex(tampered),
      valid: false,
    })
  }

  // Negative case: right signature, wrong public key.
  const a = nacl.sign.keyPair.fromSeed(bytes(32))
  const b = nacl.sign.keyPair.fromSeed(bytes(32))
  const msg = bytes(64)
  vectors.push({
    note: 'valid signature checked against a different public key',
    publicKey: hex(b.publicKey),
    message: hex(msg),
    signature: hex(nacl.sign.detached(msg, a.secretKey)),
    valid: false,
  })

  return vectors
}

// --- write ---------------------------------------------------------------------------

const files = {
  'hsalsa20.json': hsalsa20Vectors(),
  'xsalsa20.json': xsalsa20Vectors(),
  'secretbox.json': secretBoxVectors(),
  'box.json': boxVectors(),
  'x25519.json': x25519Vectors(),
  'ed25519.json': ed25519Vectors(),
}

mkdirSync(OUT_DIR, { recursive: true })
for (const [name, vectors] of Object.entries(files)) {
  const body = JSON.stringify({ origin: ORIGIN, count: vectors.length, vectors }, null, 2)
  writeFileSync(join(OUT_DIR, name), body + '\n')
  console.log(`${name.padEnd(16)} ${String(vectors.length).padStart(3)} vectors`)
}
console.log(`\nwritten to ${OUT_DIR}`)
